--- Makefile.in.orig	2005-08-27 20:22:05.000000000 +0200
+++ Makefile.in	2005-08-27 20:22:57.000000000 +0200
@@ -89,7 +89,7 @@
 install: dummy
 	$(MKINSTALLDIRS) $(DESTDIR)$(bindir)
 	$(LIBTOOL) --mode=install \
-		$(INSTALL_PROGRAM) type1afm $(bindir)/type1afm
+		$(INSTALL_PROGRAM) type1afm $(DESTDIR)$(bindir)/type1afm
 
 
 uninstall: dummy
