#!/bin/sh
# GNOME additions:
GNOMEDIR=/opt/gnome
GNOME2_PATH=/opt/gnome
PATH=$PATH:$GNOMEDIR/bin
MANPATH=$MANPATH:$GNOMEDIR/man
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$GNOMEDIR/lib/pkgconfig
LIBGLADE_MODULE_PATH=$LIBGLADE_MODULE_PATH:$GNOMEDIR/lib/libglade/2.0
ACLOCAL_FLAGS="$ACLOCAL_FLAGS -I $GNOME2_PATH/share/aclocal"
export GNOMEDIR GNOME2_PATH PATH MANPATH PKG_CONFIG_PATH LIBGLADE_MODULE_PATH ACLOCAL_FLAGS
