<?php
    include("header.php");
    include("side.php");
    include("footer.php");
?>

<?php site_header("packages"); ?>

<div id="tmiddle">

    <?php site_side(); ?>

    <!--Content-->
    <div id="tmain">
        <div class="tbox">
            <div class="ttitle">Packages</div>
            <div class="tleft">
                <p><b>Package List:</b></p>

                <blockquote>
                    <p><b>a:</b></p>
                    <ul>
                        <li>acpid-1.0.3</li>
                        <li>apmd-3.0.2</li>
                        <li>cups-1.1.22</li>
                        <li>gpm-1.20.1</li>
                    </ul>
                    <p><b>ap:</b></p>
                    <ul>
                        <li>alsa-utils-1.0.6</li>
                        <li>bash-completion-20040711</li>
                        <li>bc-1.06</li>
                        <li>cdparanoia-3.9.8</li>
                        <li>cdrdao-1.1.9</li>
                        <li>cdrtools-2.01</li>
                        <li>docbook-dsssl-stylesheets-1.79</li>
                        <li>docbook-sgml-dtd-4.2</li>
                        <li>docbook-sgml-utils-0.6.14</li>
                        <li>docbook-xml-dtd-4.1.2</li>
                        <li>docbook-xsl-stylesheets-1.66.0</li>
                        <li>enscript-1.6.4</li>
                        <li>esp-gs-7.07.1</li>
                        <li>fam-2.7.0</li>
                        <li>foomatic-db-20040918</li>
                        <li>foomatic-db-engine-3.0.2</li>
                        <li>foomatic-filters-3.0.2</li>
                        <li>gimp-print-4.2.7</li>
                        <li>gnupg-1.2.6</li>
                        <li>iptables-1.2.11</li>
                        <li>jadetex-3.13</li>
                        <li>latex2html-2002.2.1</li>
                        <li>lsof-4.72</li>
                        <li>madplay-0.15.2b</li>
                        <li>mc-4.6.0</li>
                        <li>mpg321-0.2.10</li>
                        <li>mysql-4.0.22</li>
                        <li>nano-1.2.4</li>
                        <li>openjade-1.3.2</li>
                        <li>opensp-1.5.1</li>
                        <li>pnm2ppa-1.12</li>
                        <li>screen-4.0.2</li>
                        <li>sgmlspm-1.03</li>
                        <li>sudo-1.6.8_p1</li>
                        <li>tcsh-6.13</li>
                        <li>tetex-2.0.2</li>
                        <li>vim-6.3.15</li>
                        <li>vorbis-tools-1.0.1</li>
                        <li>wv-1.0.2</li>
                        <li>wv2-0.2.2</li>
                        <li>zsh-4.2.1</li>
                    </ul>
                    <p><b>d:</b></p>
                    <ul>
                        <li>ccache-2.4</li>
                        <li>cscope-15.5</li>
                        <li>ctags-5.5.4</li>
                        <li>cvs-1.11.17</li>
                        <li>distcc-2.18.2</li>
                        <li>gettext-0.14.1</li>
                        <li>guile-1.6.4</li>
                        <li>indent-2.2.9</li>
                        <li>nasm-0.98.38</li>
                        <li>php-4.3.9</li>
                        <li>pkgconfig-0.15.0</li>
                        <li>pygtk-2.2.0</li>
                        <li>python-2.3.4</li>
                        <li>pyxml-0.8.3</li>
                        <li>ruby-1.8.1</li>
                        <li>ruby-gnome2-0.10.1</li>
                        <li>subversion-1.1.1</li>
                        <li>swig-1.3.22</li>
                        <li>tcl-8.4.7</li>
                        <li>tk-8.4.7</li>
                    </ul>
                    <p><b>emu:</b></p>
                    <ul>
                        <li>dosbox-0.62</li>
                        <li>scummvm-0.6.1b</li>
                        <li>wine-20041019</li>
                        <li>xmame-0.87</li>
                    </ul>
                    <p><b>games:</b></p>
                    <ul>
                        <li>frozen-bubble-1.0.0</li>
                    </ul>
                    <p><b>gnome:</b></p>
                    <ul>
                        <li>at-spi-1.6.0</li>
                        <li>bug-buddy-2.8.0</li>
                        <li>control-center-2.8.1</li>
                        <li>eel-2.8.1</li>
                        <li>eog-2.8.0</li>
                        <li>file-roller-2.8.3</li>
                        <li>gail-1.8.0</li>
                        <li>gal-2.2.3</li>
                        <li>gcalctool-4.4.20</li>
                        <li>gconf-2.8.1</li>
                        <li>gconf-editor-2.8.2</li>
                        <li>gdm-2.6.0.5</li>
                        <li>gedit-2.8.1</li>
                        <li>ghex-2.6.1</li>
                        <li>glade-2.6.5</li>
                        <li>gnome-2.8.0</li>
                        <li>gnome-applets-2.8.1</li>
                        <li>gnome-audio-2.0.0</li>
                        <li>gnome-desktop-2.8.1</li>
                        <li>gnome-games-2.8.1</li>
                        <li>gnome-icon-theme-2.8.0</li>
                        <li>gnome-keyring-0.4.0</li>
                        <li>gnome-media-2.8.0</li>
                        <li>gnome-mime-data-2.4.2</li>
                        <li>gnome-netstatus-2.8.0</li>
                        <li>gnome-nettool-0.99.3</li>
                        <li>gnome-panel-2.8.1</li>
                        <li>gnome-session-2.8.1</li>
                        <li>gnome-system-monitor-2.8.0</li>
                        <li>gnome-system-tools-1.0.0</li>
                        <li>gnome-terminal-2.8.0</li>
                        <li>gnome-themes-2.8.1</li>
                        <li>gnome-utils-2.8.1</li>
                        <li>gnome-vfs-2.8.2</li>
                        <li>gst-plugins-0.8.5</li>
                        <li>gstreamer-0.8.7</li>
                        <li>gthumb-2.3.3</li>
                        <li>gtk-doc-1.2</li>
                        <li>gtk-engines-2.2.0</li>
                        <li>gtk-engines-thinice-2.0.2</li>
                        <li>gtkhtml-3.2.3</li>
                        <li>gtksourceview-1.1.1</li>
                        <li>gucharmap-1.4.2</li>
                        <li>intltool-0.31.3</li>
                        <li>libbonobo-2.8.0</li>
                        <li>libbonoboui-2.8.0</li>
                        <li>libgail-gnome-1.1.0</li>
                        <li>libglade-2.4.0</li>
                        <li>libgnome-2.8.0</li>
                        <li>libgnomecanvas-2.8.0</li>
                        <li>libgnomecups-0.1.12</li>
                        <li>libgnomeprint-2.8.0.1</li>
                        <li>libgnomeprintui-2.8.0</li>
                        <li>libgnomeui-2.8.0</li>
                        <li>libgtkhtml-2.6.2</li>
                        <li>libgtop-2.8.1</li>
                        <li>libidl-0.8.4</li>
                        <li>librsvg-2.8.1</li>
                        <li>libwnck-2.8.1</li>
                        <li>metacity-2.8.6</li>
                        <li>nautilus-2.8.1</li>
                        <li>nautilus-cd-burner-2.8.3</li>
                        <li>nautilus-media-0.8.1</li>
                        <li>orbit2-2.12.0</li>
                        <li>scrollkeeper-0.3.14</li>
                        <li>vte-0.11.11</li>
                        <li>yelp-2.6.4</li>
                    </ul>
                    <p><b>kde:</b></p>
                    <ul>
                        <li>arts-1.3.1</li>
                        <li>kde-3.3.1</li>
                        <li>kdeaccessibility-3.3.1</li>
                        <li>kdeaddons-3.3.1</li>
                        <li>kdeadmin-3.3.1</li>
                        <li>kdeartwork-3.3.1</li>
                        <li>kdebase-3.3.1</li>
                        <li>kdebindings-3.3.1</li>
                        <li>kdeedu-3.3.1</li>
                        <li>kdegames-3.3.1</li>
                        <li>kdegraphics-3.3.1</li>
                        <li>kde-i18n-3.3.1</li>
                        <li>kdelibs-3.3.1</li>
                        <li>kdemultimedia-3.3.1</li>
                        <li>kdenetwork-3.3.1</li>
                        <li>kdepim-3.3.1</li>
                        <li>kdesdk-3.3.1</li>
                        <li>kdetoys-3.3.1</li>
                        <li>kdeutils-3.3.1</li>
                        <li>kdevelop-3.1.1</li>
                        <li>kdewebdev-3.3.1</li>
                        <li>koffice-1.3.4</li>
                        <li>koffice-i18n-1.3.4</li>
                        <li>quanta-3.2.3</li>
                    </ul>
                    <p><b>k:</b></p>
                    <ul>
                        <li>kernel-source-2.4.27</li>
                    </ul>
                    <p><b>l:</b></p>
                    <ul>
                        <li>aalib-1.4_rc5</li>
                        <li>alsa-driver-1.0.6a</li>
                        <li>alsa-lib-1.0.6</li>
                        <li>alsa-oss-1.0.6</li>
                        <li>aspell-0.60</li>
                        <li>atk-1.8.0</li>
                        <li>audiofile-0.2.6</li>
                        <li>courier-authlib-0.50</li>
                        <li>cyrus-sasl-2.1.19</li>
                        <li>db1-1.85</li>
                        <li>db3-3.3.11</li>
                        <li>db4-4.2.52</li>
                        <li>directfb-0.9.20</li>
                        <li>divx4linux-20030428</li>
                        <li>esound-0.2.34</li>
                        <li>evolution-data-server-1.0.2</li>
                        <li>expat-1.95.8</li>
                        <li>flac-1.1.1</li>
                        <li>fontconfig-2.2.3</li>
                        <li>freetype2-2.1.9</li>
                        <li>fribidi-0.10.4</li>
                        <li>gdbm-1.8.3</li>
                        <li>glib-1.2.10</li>
                        <li>glib2-2.4.7</li>
                        <li>gmp-4.1.2</li>
                        <li>gnet-1.1.9</li>
                        <li>gtk+-1.2.10</li>
                        <li>gtk+2-2.4.13</li>
                        <li>gtkglarea-1.99.0</li>
                        <li>hicolor-icon-theme-0.5</li>
                        <li>id3lib-3.8.3</li>
                        <li>imlib-1.9.14</li>
                        <li>imlib2-1.1.2</li>
                        <li>lame-3.96.1</li>
                        <li>lcms-1.12</li>
                        <li>lesstif-0.93.97</li>
                        <li>liba52-0.7.4</li>
                        <li>libao-0.8.5</li>
                        <li>libart_lgpl-2.3.16</li>
                        <li>libcaca-0.9</li>
                        <li>libcroco-0.6.0</li>
                        <li>libdvdcss-1.2.8</li>
                        <li>libexif-0.6.11</li>
                        <li>libfame-0.9.1</li>
                        <li>libgd-2.0.33</li>
                        <li>libgsf-1.9.1</li>
                        <li>libid3tag-0.15.1b</li>
                        <li>libieee1284-0.2.8</li>
                        <li>libjpeg-6b</li>
                        <li>libmad-0.15.1b</li>
                        <li>libmikmod-3.1.11</li>
                        <li>libmng-1.0.6</li>
                        <li>libmpeg2-0.4.0b</li>
                        <li>libmpeg3-1.5.4</li>
                        <li>libmusicbrainz-2.1.1</li>
                        <li>libogg-1.1.2</li>
                        <li>libpcap-0.8.3</li>
                        <li>libpng-1.2.7</li>
                        <li>libsoup-2.2.1</li>
                        <li>libtiff-3.7.0</li>
                        <li>libungif-4.1.2</li>
                        <li>libvorbis-1.1.0</li>
                        <li>libwmf-0.2.8.3</li>
                        <li>libwww-5.4.0</li>
                        <li>libxklavier-1.04</li>
                        <li>libxml-1.8.17</li>
                        <li>libxml2-2.6.14</li>
                        <li>libxslt-1.1.11</li>
                        <li>libzvt-2.0.1</li>
                        <li>lm_sensors-2.6.5</li>
                        <li>mhash-0.9.1</li>
                        <li>netpbm-10.25</li>
                        <li>openslp-1.0.11</li>
                        <li>pango-1.6.0</li>
                        <li>pcre-5.0</li>
                        <li>popt-1.7</li>
                        <li>qt-3.3.3</li>
                        <li>readline-4.3</li>
                        <li>sdl-1.2.7</li>
                        <li>sdl_console-2.1</li>
                        <li>sdl_gfx-2.0.11</li>
                        <li>sdl_image-1.2.3</li>
                        <li>sdl_mixer-1.2.5</li>
                        <li>sdl_net-1.2.5</li>
                        <li>sdl_perl-1.20.0</li>
                        <li>sdl_ttf-2.0.6</li>
                        <li>shared-mime-info-0.14</li>
                        <li>slang-1.4.9</li>
                        <li>smpeg-0.4.4</li>
                        <li>speex-1.0.4</li>
                        <li>startup-notification-0.7</li>
                        <li>svgalib-1.4.3</li>
                        <li>t1lib-5.0.2</li>
                        <li>taglib-1.3.1</li>
                        <li>win32codecs-20040916</li>
                        <li>wxgtk-2.5.3</li>
                        <li>xaw3d-1.5</li>
                        <li>xine-lib-1.0_rc7</li>
                        <li>xvid-1.0.2</li>
                    </ul>
                    <p><b>n:</b></p>
                    <ul>
                        <li>animail-2.0.11</li>
                        <li>apache-2.0.52</li>
                        <li>bitchx-1.1</li>
                        <li>courier-imap-3.0.8</li>
                        <li>curl-7.12.1</li>
                        <li>ethereal-0.10.7</li>
                        <li>links-2.1_pre15</li>
                        <li>lynx-2.8.5</li>
                        <li>mod_php-4.3.9</li>
                        <li>mutt-1.4.2.1</li>
                        <li>ncftp-3.1.8</li>
                        <li>neon-0.24.7</li>
                        <li>nmap-3.77</li>
                        <li>ntop-3.0</li>
                        <li>ntp-4.2.0</li>
                        <li>openssh-3.9_p1</li>
                        <li>portmap-5.0</li>
                        <li>postfix-2.1.5</li>
                        <li>proftpd-1.2.10</li>
                        <li>rsync-2.6.3</li>
                        <li>samba-3.0.8</li>
                        <li>slrn-0.9.8.0</li>
                        <li>suck-4.3.2</li>
                        <li>tcpdump-3.8.3</li>
                        <li>whois-4.6.22</li>
                        <li>xinetd-2.3.13</li>
                    </ul>
                    <p><b>xap:</b></p>
                    <ul>
                        <li>abiword-2.0.14</li>
                        <li>amule-2.0.0_rc7</li>
                        <li>anjuta-1.2.2</li>
                        <li>aterm-0.4.2</li>
                        <li>epiphany-1.4.4</li>
                        <li>evolution-2.0.2</li>
                        <li>fluxbox-0.9.10</li>
                        <li>fluxter-0.1.0</li>
                        <li>gaim-1.0.3</li>
                        <li>galeon-1.3.18</li>
                        <li>gftp-2.0.17</li>
                        <li>ggv-2.8.0</li>
                        <li>gimp-2.0.6</li>
                        <li>gkrellm-2.2.4</li>
                        <li>gnomeicu-0.99.5</li>
                        <li>gnumeric-1.2.13</li>
                        <li>gpdf-2.8.0</li>
                        <li>gqradio-1.9.1</li>
                        <li>gqview-1.4.5</li>
                        <li>gv-3.5.8</li>
                        <li>gvim-6.3.15</li>
                        <li>imagemagick-6.1.3.4</li>
                        <li>k3b-0.11.17</li>
                        <li>kcheckgmail-0.4.1</li>
                        <li>lincvs-1.3.2</li>
                        <li>lyx-1.3.5</li>
                        <li>mozilla-1.7.3</li>
                        <li>mplayer-1.0_pre5</li>
                        <li>nedit-5.5</li>
                        <li>root-tail-0.9</li>
                        <li>tvtime-0.9.14</li>
                        <li>windowmaker-0.91.0</li>
                        <li>xchat-2.4.0</li>
                        <li>xmms-1.2.10</li>
                        <li>xpdf-3.00</li>
                        <li>xscreensaver-4.18</li>
                    </ul>
                    <p><b>x:</b></p>
                    <ul>
                        <li>x11-6.8.1</li>
                        <li>xfree86-4.4.0</li>
                    </ul>
                </blockquote>
                <div class="tleft"><b>Last update: $Date: 2004/03/21 21:08:30 $</b></div>
            </div>
        </div>
    </div>
</div>

<?php site_footer(); ?>
